# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
name: aichat-media-test

services:
  aichat-media:
    extends:
      file: docker-compose.base.yml
      service: aichat-media
    command: poetry run pytest -vv $TEST_ARG
    environment:
      - TEST_ARG=${TEST_ARG}
    hostname: aichat-media
    networks:
      - aichat-media-test

networks:
  aichat-media-test:
