version: "3.8"
services:
  aichat-media:
    image: aichat-media-test
    security_opt:
      - no-new-privileges:true
    build:
      context: .
      dockerfile: Dockerfile
      target: test-builder
    command: make test
    tty: false
    stdin_open: false
    volumes:
      - ./aichat_media:/app/aichat_media
      - ./test:/app/test
    ports:
      - "8002:8000"
